server:
  http:
    addr: 127.0.0.1:8000
    timeout: 1s
  grpc:
    addr: 127.0.0.1:9000
    timeout: 1s
data:
  database:
    dns: root:root@tcp(127.0.0.1:3306)/realworld?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
jwt:
  secret: "sss111"