// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"realworld/internal/biz"
	"realworld/internal/conf"
	"realworld/internal/data"
	"realworld/internal/server"
	"realworld/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.JWT, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewMysqlDb(confData, logger)
	dataData, cleanup, err := data.NewData(db, confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger, jwt)
	userService := service.NewUserService(userUsecase)
	profileRepo := data.NewProfileRepo(dataData, logger)
	profileUsecase := biz.NewProfileUsecase(profileRepo, logger)
	profileService := service.NewProfileService(profileUsecase)
	articleRepo := data.NewArticleRepo(dataData, logger)
	commentRepo := data.NewCommentRepo(dataData, logger)
	socialUsecase := biz.NewSocialUsecase(articleRepo, profileRepo, commentRepo, logger)
	articleService := service.NewArticleService(socialUsecase)
	grpcServer := server.NewGRPCServer(confServer, userService, profileService, articleService, logger)
	httpServer := server.NewHTTPServer(confServer, userService, profileService, articleService, jwt, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
